import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F5F7FA",
    },
    headerGradient: {
        paddingHorizontal: 16,
        paddingTop: 30,
        paddingBottom: 40,
        backgroundColor: "#1976D2",
        borderBottomLeftRadius: 24,
        borderBottomRightRadius: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 6,
    },
    topBar: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    badge: {
        paddingHorizontal: 14,
        paddingVertical: 7,
        borderRadius: 16,
        backgroundColor: "#FF9800",
        shadowColor: "#FF9800",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    badgeText: {
        color: "#fff",
        fontSize: 13,
        fontWeight: "600",
        letterSpacing: 0.3,
    },
    profileArea: {
        position: "relative",
    },
    profileButton: {
        width: 38,
        height: 38,
        borderRadius: 19,
        backgroundColor: "rgba(255,255,255,0.22)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.35)",
        alignItems: "center",
        justifyContent: "center",
    },
    profileButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "700",
    },
    switcherMenu: {
        position: "absolute",
        top: 46,
        right: 0,
        width: 200,
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 8,
        zIndex: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.18,
        shadowRadius: 8,
        elevation: 8,
    },
    switcherTitle: {
        fontSize: 11,
        color: "#90A4AE",
        paddingHorizontal: 8,
        paddingVertical: 6,
        fontWeight: "600",
    },
    switcherOption: {
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 10,
        marginBottom: 6,
    },
    switcherOptionActive: {
        backgroundColor: "#E3F2FD",
    },
    switcherOptionLabel: {
        fontSize: 13,
        fontWeight: "700",
        color: "#263238",
    },
    switcherOptionSub: {
        marginTop: 2,
        fontSize: 11,
        color: "#78909C",
    },
    balanceSection: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 12,
    },
    balanceIcon: {
        width: 36,
        height: 36,
        backgroundColor: "rgba(255,255,255,0.25)",
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 10,
    },
    balanceText: {
        fontSize: 32,
        fontWeight: "700",
        color: "#fff",
        marginRight: 10,
        letterSpacing: -0.5,
    },
    balanceEye: {
        fontSize: 18,
        color: "#fff",
        opacity: 0.9,
    },
    viewDetailsText: {
        color: "rgba(255,255,255,0.85)",
        fontSize: 13,
        marginBottom: 16,
        fontWeight: "500",
        letterSpacing: 0.2,
    },
    actionButtons: {
        flexDirection: "row",
        gap: 10,
        marginTop: 8,
    },
    outlineButton: {
        borderWidth: 2,
        borderColor: "#fff",
        borderRadius: 20,
        paddingHorizontal: 14,
        paddingVertical: 9,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
    },
    outlineButtonText: {
        color: "#fff",
        fontSize: 13,
        marginLeft: 5,
        fontWeight: "600",
    },
    outlineButtonIcon: {
        fontSize: 13,
        color: "#fff",
        fontWeight: "bold",
    },
    quickActionsContainer: {
        marginHorizontal: 12,
        marginTop: -24,
        marginBottom: 20,
        borderRadius: 16,
        overflow: "hidden",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 8,
        elevation: 4,
    },
    quickActionsInner: {
        backgroundColor: "#fff",
        paddingVertical: 18,
        paddingHorizontal: 12,
    },
    quickActionsGrid: {
        flexDirection: "row",
        justifyContent: "space-around",
        flexWrap: "wrap",
    },
    actionCard: {
        alignItems: "center",
        width: "25%",
        paddingVertical: 4,
    },
    actionIcon: {
        width: 56,
        height: 56,
        backgroundColor: "#E3F2FD",
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 10,
        shadowColor: "#1976D2",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    actionLabel: {
        fontSize: 12,
        color: "#455A64",
        textAlign: "center",
        fontWeight: "600",
        letterSpacing: 0.2,
    },
    allowanceContainer: {
        marginHorizontal: 12,
        marginBottom: 20,
    },
    allowanceCardInner: {
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
        elevation: 3,
    },
    allowanceHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 16,
        paddingBottom: 14,
        borderBottomWidth: 1,
        borderBottomColor: "#F0F0F0",
    },
    allowanceTitle: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
    },
    allowanceTitleIcon: {
        width: 40,
        height: 40,
        backgroundColor: "#1976D2",
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 12,
        shadowColor: "#1976D2",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 2,
    },
    allowanceTitleText: {
        fontSize: 15,
        fontWeight: "700",
        color: "#1A1A1A",
        letterSpacing: -0.3,
    },
    allowanceSubtext: {
        fontSize: 12,
        color: "#757575",
        marginTop: 3,
        fontWeight: "500",
    },
    viewAllText: {
        fontSize: 12,
        color: "#1976D2",
        fontWeight: "700",
        letterSpacing: 0.3,
    },
    allowanceItem: {
        backgroundColor: "#F8F9FB",
        borderRadius: 12,
        padding: 14,
        marginBottom: 10,
        borderLeftWidth: 4,
        borderLeftColor: "#1976D2",
    },
    allowanceItemHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 10,
    },
    allowanceItemTitle: {
        flexDirection: "row",
        alignItems: "center",
    },
    allowanceItemIcon: {
        width: 28,
        height: 28,
        marginRight: 10,
        alignItems: "center",
        justifyContent: "center",
        fontSize: 18,
    },
    allowanceItemName: {
        fontSize: 13,
        color: "#424242",
        fontWeight: "600",
        letterSpacing: 0.2,
    },
    allowanceItemAmount: {
        fontSize: 14,
        fontWeight: "700",
        color: "#1976D2",
        letterSpacing: -0.3,
    },
    progressContainer: {
        marginVertical: 10,
    },
    allowanceStats: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 8,
    },
    allowanceStatText: {
        fontSize: 11,
        color: "#90A4AE",
        fontWeight: "600",
        letterSpacing: 0.2,
    },
    featureGridContainer: {
        marginHorizontal: 12,
        marginBottom: 24,
    },
    featureGridRow: {
        flexDirection: "row",
        gap: 12,
        marginBottom: 12,
    },
    featureCard: {
        flex: 1,
        backgroundColor: "#fff",
        borderRadius: 14,
        padding: 13,
        flexDirection: "row",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    featureIcon: {
        width: 52,
        height: 52,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 12,
        fontSize: 26,
    },
    featureContent: {
        flex: 1,
    },
    featureTitle: {
        fontSize: 13,
        fontWeight: "700",
        color: "#1A1A1A",
        marginBottom: 3,
        letterSpacing: -0.2,
    },
    featureSubtitle: {
        fontSize: 11,
        color: "#757575",
        fontWeight: "500",
        letterSpacing: 0.1,
    },
    newBadge: {
        fontSize: 9,
        color: "#FF9800",
        fontWeight: "700",
        marginTop: 4,
        letterSpacing: 0.5,
    },
    pointsText: {
        fontSize: 12,
        fontWeight: "700",
        color: "#1976D2",
        marginTop: 2,
        letterSpacing: -0.2,
    },
    contentPadding: {
        paddingBottom: 100,
    },
});

export default styles;